### ISSUE TITLE
Crashing with Spoiling Mod

### ISSUE THREAD

**Issue by RolePlayerVintage** [BTW-Community/Progressive-Item-Speedup-Addon#2]
MultiMC version: 0.7.0-3813

Launched instance in online mode

Checking Java version...
Java is version 1.8.0_351, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/instances/Cursed-Fabric-BTW-MultiMC.FoodSpoil/natives

Traits:
traits legacyLaunch
traits texturepacks
traits noapplet

Libraries:
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/instances/Cursed-Fabric-BTW-MultiMC.FoodSpoil/libraries/cursed-fabric-loader-btw-1.1.0.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/instances/Cursed-Fabric-BTW-MultiMC.FoodSpoil/libraries/intermediary-btw-1.5.2.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/instances/Cursed-Fabric-BTW-MultiMC.FoodSpoil/libraries/sponge-mixin-0.8+build.18.mod.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/com/mojang/minecraft/1.5.2/minecraft-1.5.2-client.jar

Native libraries:
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  [✔️] Better-Biomes-Addon-3.2.2.jar
  [✔️] btw-fabric-0.5.0.jar
  [✔️] craft-guide-3.0.0.jar
  [✔️] crimsons-tools-0.1.0.jar
  [✔️] dynamiclight-fabric-1.1.0.jar
  [✔️] food-spoil-addon-0.2.0.jar
  [✔️] Mobs-Enhancement-Addon-0.1.4.jar
  [✔️] progressive-item-speedup-addon-0.1.1.jar
  [✔️] tweaker-1.4.1.jar

Params:
  --username Tyranork --session token: --gameDir C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/instances/Cursed-Fabric-BTW-MultiMC.FoodSpoil/.minecraft --assetsDir C:/Users/donov/Downloads/mmc-develop-win32/MultiMC/instances/Cursed-Fabric-BTW-MultiMC.FoodSpoil/.minecraft/resources

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 5040

Using onesix launcher.

Could not find Minecraft path field.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
23:26:31.927 [main] ERROR GrossFabricHacks/main - no good? no, this man is definitely up to evil.
Loaded 5493 patches for 1424 classes
Applying patch N/A
Dec 17, 2023 11:26:32 PM net.devtech.grossfabrichacks.transformer.TransformerBootstrap <clinit>
INFO: MixinTransformer found! org.spongepowered.asm.mixin.transformer.MixinTransformer@32a541a8
Dec 17, 2023 11:26:32 PM net.devtech.grossfabrichacks.unsafe.UnsafeUtil <clinit>
INFO: UnsafeUtil init!
Dec 17, 2023 11:26:32 PM net.devtech.grossfabrichacks.transformer.TransformerBootstrap <clinit>
INFO: Unsafe casted mixin transformer success!
Applying patches to btw.BTWAddon
Duplicate local variable: e in btw.BTWAddon.loadConfigProperties()Ljava/util/Map;
    Ljava/io/FileNotFoundException; vs Ljava/io/IOException;
    Failed to fix
Duplicate local variable: propertyValue in btw.BTWAddon.repopulateConfigFile(Ljava/util/Map;)V
    Ljava/lang/String; vs Ljava/lang/String;
    Fixing...
Applying patches to net.minecraft.class_700
Applying patches to btw.world.util.WorldData
Applying patches to btw.AddonHandler
Duplicate local variable: prefix in btw.AddonHandler.onLanguageLoaded(Lnet/minecraft/class_244;)V
    Ljava/lang/String; vs Ljava/lang/String;
    Fixing...
Applying patches to net.minecraft.server.MinecraftServer
Conjuring class net.minecraft.class_738
Doing Transform2 net.minecraft.class_738
Applying patches to net.minecraft.class_738
Error: Class net.minecraft.class_738 was already transformed!
Applying patches to net.minecraft.class_738
Doing Transform2 net.minecraft.server.MinecraftServer
Class net.minecraft.server.MinecraftServer was already transformed!
Hello BTW server!
Applying patches to net.minecraft.client.MinecraftApplet
Applying patches to net.minecraft.class_343
Found Minecraft Canvas class
Applying patches to net.minecraft.class_1600
Duplicate local variable: var7 in net.minecraft.class_1600.updateDisplayMode()V
    Lorg/lwjgl/opengl/DisplayMode; vs Lorg/lwjgl/opengl/DisplayMode;
    Fixing...
Found Minecraft class
Doing Transform2 net.minecraft.class_1600
Class net.minecraft.class_1600 was already transformed!
Applying patches to net.minecraft.class_344
Hello BTW World!
Applying patches to net.minecraft.class_1555
Applying patches to net.minecraft.class_388
Applying patches to net.minecraft.class_864
Applying patches to net.minecraft.class_481
Applying patches to net.minecraft.class_518
Inconsistent constant value type: MINIMUM_GLOOM_GROWL_SOUND_CHANCE in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: MINIMUM_GLOOM_CAVE_SOUND_VOLUME in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: GLOOM_FOV_MULTIPLIER_DELTA_OUT_PER_TICK in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: GLOOM_FOV_MULTIPLIER_TIME_FOR_TRANSITION_OUT in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: MAXIMUM_GLOOM_CAVE_SOUND_VOLUME in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: MAXIMUM_GLOOM_CAVE_SOUND_CHANCE in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: MAXIMUM_GLOOM_GROWL_SOUND_VOLUME in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: MINIMUM_GLOOM_CAVE_SOUND_CHANCE in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: MAXIMUM_GLOOM_GROWL_SOUND_CHANCE in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: MINIMUM_GLOOM_GROWL_SOUND_VOLUME in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: MAXIMUM_GLOOM_FOV_MULTIPLIER in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: GLOOM_FOV_MULTIPLIER_TIME_FOR_TRANSITION_IN in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
Inconsistent constant value type: GLOOM_FOV_MULTIPLIER_DELTA_IN_PER_TICK in net.minecraft.class_518
    java.lang.Double vs F
    Fixing...
org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for pisa.mixins.json:EntityPlayerSPMixin during activity: [Attach method -> updateGloomFOVMultiplier()F]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:300)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.devtech.grossfabrichacks.transformer.TransformerBootstrap.transform(TransformerBootstrap.java:78)
	at net.devtech.grossfabrichacks.transformer.TransformerBootstrap.transformClass(TransformerBootstrap.java:68)
	at net.devtech.grossfabrichacks.transformer.TransformerBootstrap.transformClass(TransformerBootstrap.java:43)
	at org.spongepowered.asm.mixin.transformer.HackedMixinTransformer.transformClass(Unknown Source)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:158)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_343.<init>(class_343.java:20)
	at net.minecraft.client.MinecraftApplet.init(MinecraftApplet.java:20)
	at net.fabricmc.loader.entrypoint.applet.AppletLauncher.init(AppletLauncher.java:128)
	at net.fabricmc.loader.entrypoint.applet.AppletFrame.launch(AppletFrame.java:109)
	at net.fabricmc.loader.entrypoint.applet.AppletMain.main(AppletMain.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:231)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:164)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:273)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalStateException: Meta method for updateGloomFOVMultiplier not located in net.minecraft.class_518
	at org.spongepowered.asm.mixin.transformer.ClassContext.addUpgradedMethod(ClassContext.java:83)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:457)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:399)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286)
	... 43 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:231)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:164)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:273)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 10 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.devtech.grossfabrichacks.transformer.TransformerBootstrap.transformClass(TransformerBootstrap.java:45)
	at org.spongepowered.asm.mixin.transformer.HackedMixinTransformer.transformClass(Unknown Source)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:158)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_343.<init>(class_343.java:20)
	at net.minecraft.client.MinecraftApplet.init(MinecraftApplet.java:20)
	at net.fabricmc.loader.entrypoint.applet.AppletLauncher.init(AppletLauncher.java:128)
	at net.fabricmc.loader.entrypoint.applet.AppletFrame.launch(AppletFrame.java:109)
	at net.fabricmc.loader.entrypoint.applet.AppletMain.main(AppletMain.java:38)
	... 15 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.devtech.grossfabrichacks.transformer.TransformerBootstrap.transform(TransformerBootstrap.java:78)
	at net.devtech.grossfabrichacks.transformer.TransformerBootstrap.transformClass(TransformerBootstrap.java:68)
	at net.devtech.grossfabrichacks.transformer.TransformerBootstrap.transformClass(TransformerBootstrap.java:43)
	... 31 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	... 37 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for pisa.mixins.json:EntityPlayerSPMixin during activity: [Attach method -> updateGloomFOVMultiplier()F]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:300)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 37 more
Caused by: java.lang.IllegalStateException: Meta method for updateGloomFOVMultiplier not located in net.minecraft.class_518
	at org.spongepowered.asm.mixin.transformer.ClassContext.addUpgradedMethod(ClassContext.java:83)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:457)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:399)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286)
	... 43 more
Failed to invoke the Minecraft main class:
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 17 Dec 2023 23:29:25 -0600

**Comment by Arminias** [comment]
Did not use CE 2.1.2+
